# Starter pipeline
- task: FortifySCA@7
  inputs:
    licenseFile: 'C:\Users\LG\Downloads\fortify.license'
    runBuildTranslate: true
    applicationType: 'java'
    fortifyBuildId: 'test'
    runFortifyRulepackUpdate: false
    runFortifyClean: true
    scaVerbose: true
    scaDebug: true
    runFortifyScan: true
    fortifyScanType: 'Local'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
